FROM alpine

RUN apk --no-cache add xz bzip2 gzip inotify-tools coreutils && \
    mkdir /tmp/in && \
    mkdir /tmp/work && \
    mkdir /tmp/output

USER 1000

WORKDIR /tmp

COPY entrypoint.sh /tmp
ENTRYPOINT ["entrypoint.sh"]
