{
 "title": "MServer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MServer log",
   "type": "logs",
   "gridPos": { "h": 27, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=~\"/.*_mserver_\\\\d+\"} | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "MServer compress",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=~\"/.*_compress_\\\\d+\"} | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "MServer upload",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "{container_name=~\"/.*_upload_\\\\d+\"} | json | line_format \"{{.log}}\""
    }
   ]
  }
 ]
}